# Generated by Django 5.1.5 on 2025-01-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_detorder_subtotal_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.DeleteModel(
            name='DetOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
